# Generated by Django 3.0.1 on 2023-08-03 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(null=True, unique=True)),
                ('bets', models.ManyToManyField(related_name='bet_weeks', through='users.Bet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.BetWeek'),
            preserve_default=False,
        ),
    ]
