# Generated by Django 3.0.1 on 2023-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230803_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='away_team_score',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='home_team_score',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='week',
        ),
        migrations.AddField(
            model_name='bet',
            name='predicted_away_score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='predicted_home_score',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BetWeek',
        ),
    ]
