# Generated by Django 3.0.1 on 2023-08-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230823_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
