# Generated by Django 3.0.1 on 2023-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230823_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
