# Generated by Django 3.0.1 on 2023-08-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_team_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
