# Generated by Django 3.0.1 on 2023-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230831_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='over_under',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
