# Generated by Django 3.2 on 2023-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20230903_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
