# Generated by Django 3.2 on 2023-09-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_bet_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='changes_count',
            field=models.IntegerField(default=0),
        ),
    ]
